"""initial_schema

Revision ID: c1b55b2ba0be
Revises: 
Create Date: 2026-06-25 07:45:25.286357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1b55b2ba0be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('securities_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_universe', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('securities_code')
    )
    op.create_index('idx_companies_industry', 'companies', ['industry'], unique=False)
    op.create_index('idx_companies_securities_code', 'companies', ['securities_code'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('universe_coverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('traceability_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_structure_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reproducibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_workload_min', sa.Integer(), nullable=True),
    sa.Column('workload_reduction_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_snapshots_period', 'kpi_snapshots', ['period_from', 'period_to'], unique=False)
    op.create_table('scoring_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('param_kind', sa.Enum('calibrated', 'hitl_updated', name='param_kind'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backtest_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('analyst', 'manager', name='user_role'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_email')
    )
    op.create_index('idx_users_login_email', 'users', ['login_email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('yuho', 'mid_term_plan', 'timely_disclosure', 'large_shareholding', name='document_type'), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('disclosed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pbr', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('adjusted_pbr', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('equity_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('re_market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('re_book_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unrealized_gain', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unrealized_gain_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roic', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('wacc', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('stock_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_financial_data_company_date', 'financial_data', ['company_id', 'as_of_date'], unique=True)
    op.create_table('generated_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('file_kind', sa.Enum('export', 'report', name='file_kind'), nullable=False),
    sa.Column('format', sa.Enum('csv', 'excel', 'pdf', 'pptx', name='file_format'), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hitl_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Enum('hit', 'miss', name='hitl_label'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='run_status'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_screening_runs_is_current_status', 'screening_runs', ['is_current', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_sessions_token', 'sessions', ['token'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notify_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notify_channel', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_watchlist_items_user_company', 'watchlist_items', ['user_id', 'company_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('new_disclosure', 'large_shareholding', name='event_type'), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_company_id', 'events', ['company_id'], unique=False)
    op.create_index('idx_events_occurred_at', 'events', ['occurred_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_item_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('score_threshold', 'new_disclosure', 'large_shareholding', name='notification_trigger_type'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualitative_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('activist_proposal', 'capital_efficiency_target', 'sale_suggestion', 'other', name='signal_type'), nullable=False),
    sa.Column('stance', sa.Enum('support', 'counter', name='signal_stance'), nullable=False),
    sa.Column('strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recency', sa.Date(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qualitative_signals_company_id', 'qualitative_signals', ['company_id'], unique=False)
    op.create_index('idx_qualitative_signals_document_id', 'qualitative_signals', ['document_id'], unique=False)
    op.create_table('scoring_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_run_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('structure_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('event_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('event_boost', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'mid', 'low', name='confidence_level'), nullable=False),
    sa.Column('ai_judgment', sa.Text(), nullable=True),
    sa.Column('judgment_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scoring_results_run_id', 'scoring_results', ['screening_run_id'], unique=False)
    op.create_index('idx_scoring_results_total_score', 'scoring_results', ['total_score'], unique=False)
    op.create_index('uq_scoring_results_run_company', 'scoring_results', ['screening_run_id', 'company_id'], unique=True)
    op.create_table('work_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.Enum('primary_screening', 'deep_dive', 'report', 'other', name='task_type'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('screening_run_id', sa.UUID(), nullable=True),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_logs_logged_on', 'work_logs', ['logged_on'], unique=False)
    op.create_index('idx_work_logs_user_id', 'work_logs', ['user_id'], unique=False)
    op.create_table('longlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('scoring_result_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'approved', 'rejected', name='longlist_status'), nullable=False),
    sa.Column('reason_memo', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scoring_result_id'], ['scoring_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_longlist_items_status', 'longlist_items', ['status'], unique=False)
    op.create_index('uq_longlist_items_company_id', 'longlist_items', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_longlist_items_company_id', table_name='longlist_items')
    op.drop_index('idx_longlist_items_status', table_name='longlist_items')
    op.drop_table('longlist_items')
    op.drop_index('idx_work_logs_user_id', table_name='work_logs')
    op.drop_index('idx_work_logs_logged_on', table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index('uq_scoring_results_run_company', table_name='scoring_results')
    op.drop_index('idx_scoring_results_total_score', table_name='scoring_results')
    op.drop_index('idx_scoring_results_run_id', table_name='scoring_results')
    op.drop_table('scoring_results')
    op.drop_index('idx_qualitative_signals_document_id', table_name='qualitative_signals')
    op.drop_index('idx_qualitative_signals_company_id', table_name='qualitative_signals')
    op.drop_table('qualitative_signals')
    op.drop_table('notifications')
    op.drop_index('idx_events_occurred_at', table_name='events')
    op.drop_index('idx_events_company_id', table_name='events')
    op.drop_table('events')
    op.drop_index('uq_watchlist_items_user_company', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_token', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_screening_runs_is_current_status', table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_table('hitl_labels')
    op.drop_table('generated_files')
    op.drop_index('uq_financial_data_company_date', table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_table('documents')
    op.drop_index('idx_users_login_email', table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_parameters')
    op.drop_index('idx_kpi_snapshots_period', table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index('idx_companies_securities_code', table_name='companies')
    op.drop_index('idx_companies_industry', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
